### ISSUE TITLE
2025.7.0

### ISSUE THREAD

**Issue by CrallH** [JackJPowell/hass-psn#48]
When updating to 2025.7.0 this integration won't start.

Loggare: homeassistant.setup
Källa: setup.py:343
Inträffade först: 19:45:13 (1 förekomst)
Senast loggade: 19:45:13

Setup failed for custom integration 'playstation_network': Unable to import component: cannot import name 'PSNAWPBadRequestError' from 'psnawp_api.core' (/usr/local/lib/python3.13/site-packages/psnawp_api/core/__init__.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 998, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self._get_component, True
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1058, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/playstation_network/__init__.py", line 15, in <module>
    from psnawp_api.core.psnawp_exceptions import PSNAWPAuthenticationError
  File "/usr/local/lib/python3.13/site-packages/psnawp_api/__init__.py", line 1, in <module>
    from psnawp_api.psnawp import PSNAWP
  File "/usr/local/lib/python3.13/site-packages/psnawp_api/psnawp.py", line 6, in <module>
    from psnawp_api.models import Client, GameTitle, Group, SearchDomain, UniversalSearch, User
  File "/usr/local/lib/python3.13/site-packages/psnawp_api/models/__init__.py", line 1, in <module>
    from psnawp_api.models.client import Client
  File "/usr/local/lib/python3.13/site-packages/psnawp_api/models/client.py", line 6, in <module>
    from psnawp_api.models.group import Group
  File "/usr/local/lib/python3.13/site-packages/psnawp_api/models/group/__init__.py", line 14, in <module>
    from psnawp_api.models.group.group import Group
  File "/usr/local/lib/python3.13/site-packages/psnawp_api/models/group/group.py", line 9, in <module>
    from psnawp_api.core import (
    ...<3 lines>...
    )
ImportError: cannot import name 'PSNAWPBadRequestError' from 'psnawp_api.core' (/usr/local/lib/python3.13/site-packages/psnawp_api/core/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 343, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1018, in async_get_component
    self._component_future.result()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1010, in async_get_component
    comp = self._get_component()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1058, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/playstation_network/__init__.py", line 16, in <module>
    from psnawp_api.psnawp import PSNAWP
  File "/usr/local/lib/python3.13/site-packages/psnawp_api/__init__.py", line 1, in <module>
    from psnawp_api.psnawp import PSNAWP
  File "/usr/local/lib/python3.13/site-packages/psnawp_api/psnawp.py", line 6, in <module>
    from psnawp_api.models import Client, GameTitle, Group, SearchDomain, UniversalSearch, User
  File "/usr/local/lib/python3.13/site-packages/psnawp_api/models/__init__.py", line 1, in <module>
    from psnawp_api.models.client import Client
  File "/usr/local/lib/python3.13/site-packages/psnawp_api/models/client.py", line 6, in <module>
    from psnawp_api.models.group import Group
  File "/usr/local/lib/python3.13/site-packages/psnawp_api/models/group/__init__.py", line 14, in <module>
    from psnawp_api.models.group.group import Group
  File "/usr/local/lib/python3.13/site-packages/psnawp_api/models/group/group.py", line 9, in <module>
    from psnawp_api.core import (
    ...<3 lines>...
    )
ImportError: cannot import name 'PSNAWPBadRequestError' from 'psnawp_api.core' (/usr/local/lib/python3.13/site-packages/psnawp_api/core/__init__.py)

**Comment by JackJPowell** [comment]
Have you updated to version 0.8.0?

**Comment by d1zero** [comment]
I guess it's linked with native psn integration, which was released in new HA version

**Comment by CrallH** [comment]
> Have you updated to version 0.8.0?

Yes it was 0.8.0

**Comment by dnestico** [comment]
Same, I'm waiting to migrate to the native version once it has feature parity, but that seems why it's broken right now...

**Comment by ghost** [comment]
yeah, broken for me, too. I deleted the integration and removed it in HACS. After readding the playstation network integration this appears.:

![Image](https://github.com/user-attachments/assets/3d162b7c-fd72-4e3a-bf65-e6f5f311c987)

**Comment by matt0020190** [comment]
Same issue

**Comment by Tankyspanky** [comment]
Same

**Comment by SebbySullivan** [comment]
Same here even for 2025.7.1
